services:
  - type: web
    name: black-symbols-gvidon
    runtime: image
    repo: https://github.com/eknotantalya-hue/black-symbols-fairytale
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
